pipeline {
    agent any
    environment {
        VENV = 'venv'
    }
    stages {
        stage('Checkout Git') {
            steps {
                git branch: 'main', url: 'https://github.com/aishwaryacscs/test-flask.git'
            }
        }

        stage('Set up the venv') {
            steps {
                sh '''
                    python3 -m venv $VENV
                    . $VENV/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run the Tests') {
            steps {
                sh '''
                    . $VENV/bin/activate
                    python -m unittest discover -s tests
                '''
            }
        }
    }
}
