pipeline {
    agent any
    environment {
        VENV = 'venv'
    }
    stages {
        stage('Checkout git') {
            steps {
                git branch: 'main', url: 'https://github.com/aishwaryacscs/test-flask.git'
            }
        }

        stage('Set up the venv') {
            steps {
                bat '''
                    python -m venv %VENV%
                    call %VENV%\\Scripts\\activate
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run the Tests') {
            steps {
                bat '''
                    call %VENV%\\Scripts\\activate
                    python -m unittest discover -s tests
                '''
            }
        }
    }
}
